(defun sum-args (lst n)
  (let ((item (first lst))
        (tail (rest lst))
        (i (1- n)))
    (cond ((or (null lst) (eql -1 n)) 0)
          ((listp item)
           (+ (deep-sum item)
              (sum-args tail i)))
          (t (+ item (sum-args tail i))))))