(defun do-max (l)
  (do* ((result (first l))
        (sub-l (rest l) (rest sub-l))
        (item (first sub-l) (first sub-l)))
       ((null sub-l) result)
    (when (> item result)
      (setf result item))))