(defun multiply-by (lst coef)
  (let ((item (first lst))
        (tail (rest lst)))
    (cond ((null lst) nil)
          ((numberp item) 
           (cons (* item coef)
                 (multiply-by tail coef)))
          ((listp item) 
           (cons (multiply-by item coef)
                 (multiply-by tail coef)))
          (t (format t "Error: ~a is not a number" item)))))