(defun how-alike-andor (arg1 arg2)
    (or (and (or (= arg1 arg2)
                 (equal arg1 arg2))
             `the_same)
        (and (and (oddp arg1)
                  (oddp arg2))
             `both_odd)
        (and (and (evenp arg1)
                  (evenp arg2))
             `both_even)
        `difference))